package com.josedlpozo.series.repository

import android.util.Log
import com.josedlpozo.series.model.Serie
import org.jetbrains.anko.async
import java.util.*

/**
 * Created by josedelpozo on 8/3/16.
 */
class SeriesRepository{

    var series : ArrayList<Serie>? = null

    constructor(){
        series = ArrayList()
        obtainSeriesFromFakeServer()
    }

    fun obtainSeriesFromFakeServer(){
        series?.add(Serie("Game of thrones","Game of Thrones is an American fantasy drama television series created by showrunners David Benioff and D. B. Weiss. It is an adaptation of A Song of Ice and Fire, George R. R. Martin's series of fantasy novels, the first of which is titled A Game of Thrones. It is filmed in a Belfast studio and on location elsewhere in Croatia, Iceland, Malta, Morocco, Northern Ireland, Spain, Scotland, and the United States, and premiered on HBO in the United States on April 17, 2011.\n\nThe series has been renewed for a sixth season,[5] which will premiere on April 24, 2016.[6]The series is set on the fictional continents of Westeros and Essos, and interweaves several plot lines with a large ensemble cast. The first narrative arc follows a civil war among several noble houses for the Iron Throne of the Seven Kingdoms; the second covers the attempts to reclaim the throne by the exiled last scion of the realm's deposed ruling dynasty; the third chronicles the rising threat of the impending winter and the legendary creatures and fierce peoples of the North.\n\nGame of Thrones has attracted record numbers of viewers on HBO and attained an exceptionally broad and active international fan base. It has received widespread acclaim by critics, particularly for its acting, complex characters, story, scope, and production values, although its frequent use of nudity, violence, and sexual violence has attracted criticism. The series has won 26 Primetime Emmy Awards, including the Primetime Emmy Award for Outstanding Drama Series in 2015—when it set a record for most wins for a series in a single year—and numerous other awards and nominations, including three Hugo Award for Best Dramatic Presentation, a Peabody Award, and three Golden Globe Award nominations. From among the ensemble cast, Peter Dinklage won two Emmy Awards for Outstanding Supporting Actor in a Drama Series and a Golden Globe Award for Best Supporting Actor – Series, Miniseries or Television Film for his performance as Tyrion Lannister.", "http://www.eliberico.com/wp-content/uploads/2015/02/juego-de-tronos.jpg"))

        series?.add(Serie("Dexter","Dexter is an American television crime drama mystery series that aired on Showtime from October 1, 2006, to September 22, 2013.[1] Set in Miami, the series centers on Dexter Morgan (Michael C. Hall), a forensic technician specializing in blood spatter pattern analysis for the fictional Miami Metro Police Department, who leads a secret parallel life as a vigilante serial killer, hunting down murderers who have slipped through the cracks of the justice system. The show's first season was derived from the novel Darkly Dreaming Dexter (2004), the first of the Dexter series novels by Jeff Lindsay. It was adapted for television by screenwriter James Manos, Jr., who wrote the first episode. Subsequent seasons evolved independently of Lindsay's works.\n\nIn February 2008, reruns (edited down to a TV-14 rating) began to air on CBS, although the reruns on CBS ended after one run of the first season. The series has enjoyed mostly positive reviews throughout its run and popularity, including four straight Primetime Emmy nominations for Best Drama series in its first four seasons. Season 4 aired its season finale on December 13, 2009, to a record-breaking audience of 2.6 million viewers, making it the most-watched original series episode ever on Showtime at that time.[2][3]\n\nIn April 2013, Showtime announced that Season 8 would be the final season of Dexter.[4] The Season 8 premiere was the most watched Dexter episode with more than 3 million viewers total for all airings that night.[5] The original broadcast of the series finale—shown at 9 p.m. on September 22, 2013—drew 2.8 million viewers, the largest overall audience in Showtime's history.[6]", "http://static.wixstatic.com/media/9625d4_a90f01cd5cba493daf744a9dce034b7d.jpg"))

        series?.add(Serie("Lost","Lost is an American television drama series that originally aired on the American Broadcasting Company (ABC) from September 22, 2004, to May 23, 2010, over six seasons, comprising a total of 121 episodes. Lost is a drama series containing elements of science fiction and the supernatural. It follows the survivors of the crash of a commercial passenger jet, flying between Sydney and Los Angeles, on a mysterious tropical island somewhere in the South Pacific Ocean. The story is told in a heavily serialized manner. Episodes typically feature a primary storyline set on the island, augmented by flashback or flashforward sequences which provide additional insight into the involved characters.\n\nLost was created by Jeffrey Lieber, J.J. Abrams and Damon Lindelof, who share story-writing credits for the pilot episode, which Abrams directed. Throughout the show's run, Lindelof and Carlton Cuse served as showrunners and head writers, working together with a large number of other executive producers and writers. Due to its large ensemble cast and the cost of filming primarily on location in Oahu, Hawaii, the series was one of the most expensive on television, with the pilot alone costing over $14 million.[1] The fictional universe and mythology of Lost are expanded upon by a number of related media, most importantly, a series of short mini-episodes called Missing Pieces, and a 12-minute epilogue titled \"The New Man in Charge\".\n\nA critically acclaimed and popular success, Lost has been consistently ranked by critics on their lists of the top ten television series of all time.[2] The first season garnered an estimated average of 16 million viewers per episode on ABC.[3] During its sixth and final season, the show averaged over 11 million U.S. viewers per episode. Lost was the recipient of hundreds of industry award nominations throughout its run and won numerous of these awards, including the Emmy Award for Outstanding Drama Series in 2005,[4] Best American Import at the British Academy Television Awards in 2005, the Golden Globe Award for Best Drama in 2006, and a Screen Actors Guild Award for Outstanding Ensemble in a Drama Series. Lost was declared the highest-rated show for the first ten years of IMDb.com Pro (2002–2012).[5]", "http://vignette4.wikia.nocookie.net/lostpedia/images/a/aa/Lost-season1.png/revision/latest?cb=20061010033648&path-prefix=es"))

        series?.add(Serie("Breaking bad","Breaking Bad is an American crime drama television series created and produced by Vince Gilligan. The show originally aired on the AMC network for five seasons, from January 20, 2008, to September 29, 2013. It tells the story of Walter White (Bryan Cranston), a struggling high school chemistry teacher diagnosed with inoperable lung cancer. Together with his former student Jesse Pinkman (Aaron Paul), White turns to a life of crime, producing and selling crystallized methamphetamine to secure his family's financial future before he dies, while navigating the dangers of the criminal world. The title is from a Southern colloquialism meaning to \"raise hell\". Breaking Bad is set and was filmed in Albuquerque, New Mexico.\n\nWalter's family consists of his wife Skyler (Anna Gunn) and children, Walter, Jr. (RJ Mitte) and Holly (Elanor Anne Wenrich). The show also features Skyler's sister Marie Schrader (Betsy Brandt), and her husband Hank (Dean Norris), a Drug Enforcement Administration (DEA) agent. Walter hires lawyer Saul Goodman (Bob Odenkirk), who connects him with private investigator and fixer Mike Ehrmantraut (Jonathan Banks) and in turn Mike's employer, drug kingpin Gus Fring (Giancarlo Esposito). The final season introduces the characters of Todd Alquist (Jesse Plemons) and Lydia Rodarte-Quayle (Laura Fraser).\n\nBreaking Bad is widely regarded as one of the greatest television series of all time. By the time the series finale aired, the series was among the most-watched cable shows on American television. The show received numerous awards, including sixteen Primetime Emmy Awards, eight Satellite Awards, two Golden Globe Awards, two Peabody Awards, two Critics' Choice Awards, and four Television Critics Association Awards. For his leading performance, Cranston won the Primetime Emmy Award for Outstanding Lead Actor in a Drama Series four times, while Aaron Paul won the Primetime Emmy Award for Outstanding Supporting Actor in a Drama Series three times. In 2013, Breaking Bad entered the Guinness World Records as the most critically acclaimed show of all time.", "http://nbc.com.co/wp-content/uploads/2015/10/breaking-bad-season6-750x525.png"))
    }

    fun getAll() : ArrayList<Serie>?{
        return series
    }

    fun getByName(name: String) : Serie{
        series?.forEach {
            if(it.name.equals(name)) return it
        }
        return series?.get(0)!!
    }

}